export interface RoleCategory {
  id: string;
  name: string;
  description: string;
  roles: string[];
}

export const ROLE_CATEGORIES: readonly RoleCategory[] = [
  {
    id: 'foncier',
    name: 'Professionnels du foncier',
    description: 'Expertise foncière, bornage, topographie et conformité domaniale',
    roles: [
      'Géomètre-expert',
      'Topographe',
      'Cabinet de géomètres-topographes',
      'Agent foncier',
      'Consultant foncier',
      'Lotisseur agréé',
      'Aménageur foncier',
      'Expert immobilier',
      'Évaluateur foncier',
      'Spécialiste de la viabilisation',
      'Expert en bornage et morcellement',
      'Consultant en titres fonciers, ACD et procédures domaniales',
    ],
  },
  {
    id: 'btp_ingenierie',
    name: 'Professionnels du BTP',
    description: 'Ingénierie, direction de travaux, études de prix et contrôle technique',
    roles: [
      'Ingénieur en génie civil',
      'Ingénieur en bâtiment',
      'Ingénieur en travaux publics',
      'Ingénieur en structures',
      'Ingénieur en hydraulique',
      'Ingénieur en routes et ouvrages d’art',
      'Ingénieur électricien bâtiment',
      'Ingénieur en électromécanique',
      'Ingénieur en énergie solaire',
      'Conducteur de travaux',
      'Chef de chantier',
      'Chef de projet BTP',
      'Métreur-vérificateur',
      'Économiste de la construction',
      'Technicien supérieur en bâtiment',
      'Technicien en génie civil',
      'Dessinateur-projeteur',
      'Projeteur BIM',
      'Modeleur BIM',
      'Coordinateur BIM',
      'Planificateur de chantier',
      'Contrôleur technique',
      'Responsable QHSE/HSE',
      'Coordinateur sécurité de chantier',
      'Laborantin BTP',
      'Technicien de laboratoire géotechnique',
      'Géotechnicien',
      'Expert en matériaux de construction',
    ],
  },
  {
    id: 'architecture',
    name: 'Architecture et conception',
    description: 'Plans, permis de construire, aménagement d’espace et urbanisme',
    roles: [
      'Architecte',
      'Cabinet d’architecture',
      'Architecte d’intérieur',
      'Décorateur d’intérieur',
      'Urbaniste',
      'Paysagiste',
      'Designer d’espaces',
      'Designer 3D',
      'Infographiste spécialisé en architecture',
      'Maquettiste',
      'Dessinateur en bâtiment',
      'Bureau d’études techniques (BET)',
      'Bureau d’études structures',
      'Bureau d’études fluides',
      'Bureau d’études électricité',
      'Bureau d’études VRD',
      'Cabinet d’ingénierie',
      'Consultant en permis de construire',
    ],
  },
  {
    id: 'artisans_chantier',
    name: 'Entreprises et artisans de chantier',
    description: 'Gros œuvre, second œuvre, finitions et corps d’état techniques',
    roles: [
      'Entreprise générale de construction',
      'Entreprise de BTP',
      'Entreprise de rénovation',
      'Promoteur constructeur',
      'Sous-traitant BTP',
      'Maçon',
      'Coffreur',
      'Ferrailleur',
      'Charpentier',
      'Menuisier bois',
      'Menuisier aluminium',
      'Menuisier métallique',
      'Soudeur',
      'Vitrier',
      'Plombier',
      'Électricien bâtiment',
      'Climaticien et frigoriste',
      'Carreleur',
      'Peintre en bâtiment',
      'Staffeur',
      'Plafonneur',
      'Étanchéiste',
      'Façadier',
      'Couvreur',
      'Serrurier',
      'Poseur de pavés',
      'Poseur de faux plafonds',
      'Poseur de cuisines et dressings',
      'Installateur de portails automatiques',
      'Installateur de caméras de surveillance',
      'Installateur d’alarmes',
      'Installateur de systèmes domotiques',
      'Installateur de panneaux solaires',
      'Foreur et spécialiste de forage',
      'Constructeur de piscines',
      'Paysagiste et jardinier professionnel',
      'Entreprise de nettoyage de fin de chantier',
      'Entreprise de démolition',
      'Entreprise de traitement des déchets de chantier',
    ],
  },
  {
    id: 'immobilier',
    name: 'Professionnels de l’immobilier',
    description: 'Transactions, négociation, gestion locative et syndics',
    roles: [
      'Agent immobilier',
      'Agence immobilière',
      'Courtier immobilier',
      'Mandataire immobilier',
      'Conseiller immobilier',
      'Chasseur immobilier',
      'Négociateur immobilier',
      'Promoteur immobilier',
      'Lotisseur et aménageur',
      'Gestionnaire de biens immobiliers',
      'Administrateur de biens',
      'Syndic de copropriété',
      'Gestionnaire locatif',
      'Conciergerie immobilière',
      'Expert en estimation immobilière',
      'Photographe immobilier',
      'Vidéaste immobilier',
      'Home stager',
      'Consultant en investissement immobilier',
      'Conseiller en immobilier de la diaspora',
      'Gestionnaire de résidences et de cités immobilières',
    ],
  },
  {
    id: 'juridique',
    name: 'Juridique et sécurisation',
    description: 'Notariat, conseil en droit immobilier et médiation foncière',
    roles: [
      'Notaire',
      'Cabinet notarial',
      'Avocat spécialisé en droit immobilier',
      'Avocat spécialisé en droit foncier',
      'Huissier de justice',
      'Commissaire de justice',
      'Juriste immobilier',
      'Juriste foncier',
      'Conseiller juridique',
      'Médiateur immobilier',
      'Expert judiciaire immobilier',
      'Expert judiciaire en bâtiment',
      'Consultant en conformité foncière',
      'Spécialiste des litiges fonciers',
      'Spécialiste de la documentation immobilière',
      'Spécialiste des démarches ACD et titre foncier',
    ],
  },
  {
    id: 'finance_assurance',
    name: 'Finance et assurance',
    description: 'Financement bancaire, crédits immobiliers, garanties et assurances',
    roles: [
      'Banque (Crédit immobilier)',
      'Institution de microfinance',
      'Courtier en crédit immobilier',
      'Conseiller en financement de projet',
      'Investisseur immobilier',
      'Fonds d’investissement immobilier',
      'Assureur habitation',
      'Assureur chantier',
      'Assureur responsabilité civile professionnelle',
      'Assureur dommages-ouvrage',
      'Courtier en assurance',
      'Expert-comptable',
      'Comptable spécialisé BTP',
      'Commissaire aux comptes',
      'Fiscaliste immobilier',
      'Conseiller en fiscalité foncière',
    ],
  },
  {
    id: 'fournisseurs_materiaux',
    name: 'Fournisseurs et logistique',
    description: 'Matériaux de construction, équipements, engins lourds et transport',
    roles: [
      'Quincaillerie',
      'Magasin de matériaux de construction',
      'Fournisseur de ciment',
      'Fournisseur de fer et acier',
      'Fournisseur de sable, gravier et agrégats',
      'Fournisseur de béton prêt à l’emploi',
      'Fabricant de briques et parpaings',
      'Fournisseur de menuiserie',
      'Fournisseur de peinture',
      'Fournisseur de carrelage et revêtements',
      'Fournisseur de matériel électrique',
      'Fournisseur de plomberie',
      'Fournisseur de climatisation',
      'Fournisseur de solutions solaires',
      'Loueur d’engins de chantier',
      'Loueur d’échafaudages',
      'Loueur de bennes',
      'Transporteur de matériaux',
      'Entreprise de logistique BTP',
      'Concessionnaire d’engins lourds',
      'Mécanicien d’engins de chantier',
      'Station de pesage et contrôle des matériaux',
    ],
  },
  {
    id: 'formation_emploi',
    name: 'Formation et emploi',
    description: 'Écoles, universités, cabinets de recrutement et étudiants',
    roles: [
      'Formateur BTP',
      'Formateur AutoCAD / Revit / BIM',
      'Formateur en topographie',
      'Formateur en métré et étude de prix',
      'Formateur en gestion de chantier',
      'Formateur en sécurité chantier',
      'École technique et professionnelle',
      'Lycée technique',
      'Centre de formation professionnelle',
      'Université et grande école',
      'Responsable pédagogique BTP',
      'Étudiant en BTP',
      'Stagiaire en génie civil',
      'Recruteur spécialisé BTP',
      'Cabinet de recrutement',
      'Organisme de certification',
      'Association professionnelle BTP',
      'Chambre sectorielle',
    ],
  },
] as const;

export interface QuickRoleType {
  id: 'particulier' | 'professionnel' | 'entreprise' | 'geometre';
  label: string;
  subLabel: string;
  defaultCategory: string;
}

export const QUICK_ROLE_TYPES: readonly QuickRoleType[] = [
  {
    id: 'particulier',
    label: 'Particulier',
    subLabel: 'Propriétaire ou acheteur',
    defaultCategory: 'particulier',
  },
  {
    id: 'professionnel',
    label: 'Professionnel',
    subLabel: 'Artisan ou indépendant',
    defaultCategory: 'btp_ingenierie',
  },
  {
    id: 'entreprise',
    label: 'Entreprise',
    subLabel: 'Société BTP ou Agence',
    defaultCategory: 'artisans_chantier',
  },
  {
    id: 'geometre',
    label: 'Géomètre / Expert',
    subLabel: 'Foncier, notaire ou BET',
    defaultCategory: 'foncier',
  },
] as const;
