export interface RoleCategory {
  id: string;
  name: string;
  description: string;
  roles: string[];
}

export const ROLE_CATEGORIES: readonly RoleCategory[] = [
  {
    id: 'particulier',
    name: 'PARTICULIER',
    description: 'Propriétaire, acquéreur ou porteur de projet immobilier',
    roles: [
      'Propriétaire ou acheteur particulier',
      'Acquéreur de terrain ou maison',
      'Porteur de projet de construction',
      'Bailleur particulier',
    ],
  },
  {
    id: 'foncier',
    name: 'Professionnels du foncier',
    description: 'Expertise foncière, bornage, topographie et conformité domaniale',
    roles: [
      'Géomètres-experts',
      'Topographes',
      'Cabinets de géomètres-topographes',
      'Agents fonciers',
      'Consultants fonciers',
      'Lotisseurs agréés',
      'Aménageurs fonciers',
      'Experts immobiliers',
      'Évaluateurs fonciers',
      'Spécialistes de la viabilisation',
      'Experts en bornage et morcellement',
      'Consultants en titres fonciers, ACD et procédures domaniales',
    ],
  },
  {
    id: 'btp_ingenierie',
    name: 'Professionnels du BTP',
    description: 'Ingénierie, direction de travaux, études de prix et contrôle technique',
    roles: [
      'Ingénieurs en génie civil',
      'Ingénieurs en bâtiment',
      'Ingénieurs en travaux publics',
      'Ingénieurs en structures',
      'Ingénieurs en hydraulique',
      'Ingénieurs en routes et ouvrages d’art',
      'Ingénieurs électriciens bâtiment',
      'Ingénieurs en électromécanique',
      'Ingénieurs en énergie solaire',
      'Conducteurs de travaux',
      'Chefs de chantier',
      'Chefs de projet BTP',
      'Métreurs-vérificateurs',
      'Économistes de la construction',
      'Techniciens supérieurs en bâtiment',
      'Techniciens en génie civil',
      'Dessinateurs-projeteurs',
      'Projeteurs BIM',
      'Modeleurs BIM',
      'Coordinateurs BIM',
      'Planificateurs de chantier',
      'Contrôleurs techniques',
      'Responsables qualité, hygiène, sécurité et environnement (QHSE/HSE)',
      'Coordinateurs sécurité de chantier',
      'Laborantins BTP',
      'Techniciens de laboratoire géotechnique',
      'Géotechniciens',
      'Experts en matériaux de construction',
    ],
  },
  {
    id: 'architecture',
    name: 'Architecture et conception',
    description: 'Plans, permis de construire, aménagement d’espace et urbanisme',
    roles: [
      'Architectes',
      'Cabinets d’architecture',
      'Architectes d’intérieur',
      'Décorateurs d’intérieur',
      'Urbanistes',
      'Paysagistes',
      'Designers d’espaces',
      'Designers 3D',
      'Infographistes spécialisés en architecture',
      'Maquettistes',
      'Dessinateurs en bâtiment',
      'Bureaux d’études techniques (BET)',
      'Bureaux d’études structures',
      'Bureaux d’études fluides',
      'Bureaux d’études électricité',
      'Bureaux d’études VRD (voirie et réseaux divers)',
      'Cabinets d’ingénierie',
      'Consultants en permis de construire',
    ],
  },
  {
    id: 'artisans_chantier',
    name: 'Entreprises et artisans de chantier',
    description: 'Gros œuvre, second œuvre, finitions et corps d’état techniques',
    roles: [
      'Entreprises générales de construction',
      'Entreprises de BTP',
      'Entreprises de rénovation',
      'Promoteurs constructeurs',
      'Sous-traitants BTP',
      'Maçons',
      'Coffreurs',
      'Ferrailleurs',
      'Charpentiers',
      'Menuisiers bois',
      'Menuisiers aluminium',
      'Menuisiers métalliques',
      'Soudeurs',
      'Vitriers',
      'Plombiers',
      'Électriciens bâtiment',
      'Climaticiens et frigoristes',
      'Carreleurs',
      'Peintres en bâtiment',
      'Staffeurs',
      'Plafonneurs',
      'Étanchéistes',
      'Façadiers',
      'Couvreurs',
      'Serruriers',
      'Poseurs de pavés',
      'Poseurs de faux plafonds',
      'Poseurs de cuisines et dressings',
      'Installateurs de portails automatiques',
      'Installateurs de caméras de surveillance',
      'Installateurs d’alarmes',
      'Installateurs de systèmes domotiques',
      'Installateurs de panneaux solaires',
      'Foreurs et spécialistes de forage',
      'Constructeurs de piscines',
      'Paysagistes et jardiniers professionnels',
      'Entreprises de nettoyage de fin de chantier',
      'Entreprises de démolition',
      'Entreprises de traitement des déchets de chantier',
    ],
  },
  {
    id: 'immobilier',
    name: 'Professionnels de l’immobilier',
    description: 'Transactions, négociation, gestion locative et syndics',
    roles: [
      'Agents immobiliers',
      'Agences immobilières',
      'Courtiers immobiliers',
      'Mandataires immobiliers',
      'Conseillers immobiliers',
      'Chasseurs immobiliers',
      'Négociateurs immobiliers',
      'Promoteurs immobiliers',
      'Lotisseurs et aménageurs',
      'Gestionnaires de biens immobiliers',
      'Administrateurs de biens',
      'Syndics de copropriété',
      'Gestionnaires locatifs',
      'Conciergeries immobilières',
      'Experts en estimation immobilière',
      'Photographes immobiliers',
      'Vidéastes immobiliers',
      'Home stagers',
      'Consultants en investissement immobilier',
      'Conseillers en immobilier de la diaspora',
      'Gestionnaires de résidences et de cités immobilières',
    ],
  },
  {
    id: 'juridique',
    name: 'Juridique et sécurisation',
    description: 'Notariat, conseil en droit immobilier et médiation foncière',
    roles: [
      'Notaires',
      'Cabinets notariaux',
      'Avocats spécialisés en droit immobilier',
      'Avocats spécialisés en droit foncier',
      'Huissiers de justice',
      'Commissaires de justice',
      'Juristes immobiliers',
      'Juristes fonciers',
      'Conseillers juridiques',
      'Médiateurs immobiliers',
      'Experts judiciaires immobiliers',
      'Experts judiciaires en bâtiment',
      'Consultants en conformité foncière',
      'Spécialistes des litiges fonciers',
      'Spécialistes de la documentation immobilière',
      'Spécialistes des démarches ACD et titre foncier',
    ],
  },
  {
    id: 'finance_assurance',
    name: 'Finance et assurance',
    description: 'Financement bancaire, crédits immobiliers, garanties et assurances',
    roles: [
      'Banques proposant des crédits immobiliers',
      'Institutions de microfinance',
      'Courtiers en crédit immobilier',
      'Conseillers en financement de projet',
      'Investisseurs immobiliers',
      'Fonds d’investissement immobilier',
      'Assureurs habitation',
      'Assureurs chantier',
      'Assureurs responsabilité civile professionnelle',
      'Assureurs dommages-ouvrage',
      'Courtiers en assurance',
      'Experts-comptables',
      'Comptables spécialisés BTP',
      'Commissaires aux comptes',
      'Fiscalistes immobiliers',
      'Conseillers en fiscalité foncière',
    ],
  },
  {
    id: 'fournisseurs_materiaux',
    name: 'Fournisseurs et logistique',
    description: 'Matériaux de construction, équipements, engins lourds et transport',
    roles: [
      'Quincailleries',
      'Magasins de matériaux de construction',
      'Fournisseurs de ciment',
      'Fournisseurs de fer et acier',
      'Fournisseurs de sable, gravier et agrégats',
      'Fournisseurs de béton prêt à l’emploi',
      'Fabricants de briques et parpaings',
      'Fournisseurs de menuiserie',
      'Fournisseurs de peinture',
      'Fournisseurs de carrelage et revêtements',
      'Fournisseurs de matériel électrique',
      'Fournisseurs de plomberie',
      'Fournisseurs de climatisation',
      'Fournisseurs de solutions solaires',
      'Loueurs d’engins de chantier',
      'Loueurs d’échafaudages',
      'Loueurs de bennes',
      'Transporteurs de matériaux',
      'Entreprises de logistique BTP',
      'Concessionnaires d’engins lourds',
      'Mécaniciens d’engins de chantier',
      'Stations de pesage et services de contrôle des matériaux',
    ],
  },
  {
    id: 'formation_emploi',
    name: 'Formation et emploi',
    description: 'Écoles, universités, formateurs et recrutement spécialisé BTP',
    roles: [
      'Formateurs BTP',
      'Formateurs AutoCAD',
      'Formateurs Revit et BIM',
      'Formateurs en topographie',
      'Formateurs en métré et étude de prix',
      'Formateurs en gestion de chantier',
      'Formateurs en sécurité chantier',
      'Écoles techniques et professionnelles',
      'Lycées techniques',
      'Centres de formation professionnelle',
      'Universités et grandes écoles',
      'Responsables pédagogiques BTP',
      'Étudiants en BTP',
      'Stagiaires en génie civil',
      'Recruteurs spécialisés BTP',
      'Cabinets de recrutement',
      'Organismes de certification',
      'Associations professionnelles BTP',
      'Chambres et organisations sectorielles',
    ],
  },
] as const;
